# named list of all robots
robots:
  drone1:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E701
    initial_position: [0, 0, 0]
    type: cf21  # see robot_types
  drone2:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E702
    initial_position: [0, 1., 0]
    type: cf21  # see robot_types
  drone3:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E703
    initial_position: [0, -1., 0]
    type: cf21  # see robot_types
  drone4:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E704
    initial_position: [1, 0., 0]
    type: cf21  # see robot_types
    #firmware_logging:
    #  enabled: true
    #  default_topics:
    #  pose:
    #    frequency: 1 # Hz
    #  custom_topics:
    #    topic_name3: 
    #      frequency: 100
    #      vars: ["acc.x", "acc.y", "acc.z"]"""
  drone5:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E705
    initial_position: [-1, 0., 0]
    type: cf21  # see robot_types
  drone6:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E706
    initial_position: [-0.24, -1.5, 0]
    type: cf21  # see robot_types
  drone7:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E707
    initial_position: [-1., -1., 0]
    type: cf21  # see robot_types
  drone8:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E708
    initial_position: [0, 0., 0]
    type: cf21  # see robot_types
  drone9:
    enabled: false
    uri: radio://0/80/2M/E7E7E7E709
    initial_position: [-2, 0., 0]
    type: cf21  # see robot_types
  drone10:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E710
    initial_position: [0, 2., 0]
    type: cf21  # see robot_types
# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: false
      # only if enabled; see motion_capture.yaml
      marker: default_single_marker
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V
    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5
    #firmware_logging:
    #   enabled: true
    #   default_topics:
    #   pose:
    #     frequency: 1 # Hz
    #   custom_topics:
    #    topic_name3: 
    #      frequency: 1
    #      vars: ["acc.x", "acc.y", "acc.z"]

  cf21_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: mocap_deck
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

    # firmware_params:
    #   kalman:
    #     pNAcc_xy: 1.0 # default 0.5

# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    default_topics:
     # remove to disable default topic
      pose:
        frequency: 100 # Hz
      #odom:
      #  frequency: 100 # Hz
    #ustom_topics:
    #  topic_name1:
    #    frequency: 10 # Hz
    #    vars: ["stateEstimateZ.x", "stateEstimateZ.y", "stateEstimateZ.z", "pm.vbat"]
    #  topic_name2:
    #    frequency: 1 # Hz
    #    vars: ["stabilizer.roll", "stabilizer.pitch", "stabilizer.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 1 # 1: PID, 2: mellinger
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    kalman:
      pNVel: 0.3
      mNGyro_rollpitch: 0.4

  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
